/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.PhoneNumberController;
const NumberType2Enum = testerlib.NumberType2Enum;
const NumberTypeEnum = testerlib.NumberTypeEnum;
const Numbertype1Enum = testerlib.Numbertype1Enum;

describe("PhoneNumberController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Retrieve a list of purchased phones numbers associated with your Ytel account.
     */
    it("should testTestListNumbers response", function testTestListNumbersTest(done) {
        // parameters for the API call
        let page = null;
        let pageSize = null;
        let numberType = null;
        let friendlyName = null;

        controller.createListNumbers(page, pageSize, numberType, friendlyName, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            // test headers
            let headers = [];
            headers['Content-Type'] = 'application/json';
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            done();
        });
    });

});
