/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.VoiceController;
const Status1Enum = testerlib.Status1Enum;
const AudioDirectionEnum = testerlib.AudioDirectionEnum;
const Direction1Enum = testerlib.Direction1Enum;
const DirectionEnum = testerlib.DirectionEnum;
const FileformatEnum = testerlib.FileformatEnum;
const PlayDtmfDirectionEnum = testerlib.PlayDtmfDirectionEnum;
const GroupConfirmFileEnum = testerlib.GroupConfirmFileEnum;
const IfMachineEnum = testerlib.IfMachineEnum;

describe("VoiceController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * A list of calls associated with your Ytel account
     */
    it("should testTestListCalls response", function testTestListCallsTest(done) {
        // parameters for the API call
        let page = null;
        let pageSize = null;
        let to = null;
        let from = null;
        let dateCreated = null;

        controller.createListCalls(page, pageSize, to, from, dateCreated, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            // test headers
            let headers = [];
            headers['Content-Type'] = 'application/json';
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            done();
        });
    });

});
