/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body40
 */
class Body40 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.shortcode = this.constructor.getValue(obj.shortcode);
        this.to = this.constructor.getValue(obj.to);
        this.templateid = this.constructor.getValue(obj.templateid);
        this.data = this.constructor.getValue(obj.data);
        this.method = this.constructor.getValue(obj.method || obj.Method);
        this.messageStatusCallback =
          this.constructor.getValue(obj.messageStatusCallback
     || obj.MessageStatusCallback);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'shortcode', realName: 'shortcode' },
            { name: 'to', realName: 'to' },
            { name: 'templateid', realName: 'templateid' },
            { name: 'data', realName: 'data' },
            { name: 'method', realName: 'Method' },
            { name: 'messageStatusCallback', realName: 'MessageStatusCallback' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body40;
