/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body77
 */
class Body77 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.from = this.constructor.getValue(obj.from || obj.From);
        this.to = this.constructor.getValue(obj.to || obj.To);
        this.url = this.constructor.getValue(obj.url || obj.Url);
        this.groupConfirmKey =
          this.constructor.getValue(obj.groupConfirmKey
     || obj.GroupConfirmKey);
        this.groupConfirmFile =
          this.constructor.getValue(obj.groupConfirmFile
     || obj.GroupConfirmFile);
        this.method = this.constructor.getValue(obj.method || obj.Method);
        this.statusCallBackUrl =
          this.constructor.getValue(obj.statusCallBackUrl
     || obj.StatusCallBackUrl);
        this.statusCallBackMethod =
          this.constructor.getValue(obj.statusCallBackMethod
     || obj.StatusCallBackMethod);
        this.fallBackUrl = this.constructor.getValue(obj.fallBackUrl || obj.FallBackUrl);
        this.fallBackMethod = this.constructor.getValue(obj.fallBackMethod || obj.FallBackMethod);
        this.heartBeatUrl = this.constructor.getValue(obj.heartBeatUrl || obj.HeartBeatUrl);
        this.heartBeatMethod =
          this.constructor.getValue(obj.heartBeatMethod
     || obj.HeartBeatMethod);
        this.timeout = this.constructor.getValue(obj.timeout || obj.Timeout);
        this.playDtmf = this.constructor.getValue(obj.playDtmf || obj.PlayDtmf);
        this.hideCallerId = this.constructor.getValue(obj.hideCallerId || obj.HideCallerId);
        this.record = this.constructor.getValue(obj.record || obj.Record);
        this.recordCallBackUrl =
          this.constructor.getValue(obj.recordCallBackUrl
     || obj.RecordCallBackUrl);
        this.recordCallBackMethod =
          this.constructor.getValue(obj.recordCallBackMethod
     || obj.RecordCallBackMethod);
        this.transcribe = this.constructor.getValue(obj.transcribe || obj.Transcribe);
        this.transcribeCallBackUrl =
          this.constructor.getValue(obj.transcribeCallBackUrl
     || obj.TranscribeCallBackUrl);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'from', realName: 'From' },
            { name: 'to', realName: 'To' },
            { name: 'url', realName: 'Url' },
            { name: 'groupConfirmKey', realName: 'GroupConfirmKey' },
            { name: 'groupConfirmFile', realName: 'GroupConfirmFile' },
            { name: 'method', realName: 'Method' },
            { name: 'statusCallBackUrl', realName: 'StatusCallBackUrl' },
            { name: 'statusCallBackMethod', realName: 'StatusCallBackMethod' },
            { name: 'fallBackUrl', realName: 'FallBackUrl' },
            { name: 'fallBackMethod', realName: 'FallBackMethod' },
            { name: 'heartBeatUrl', realName: 'HeartBeatUrl' },
            { name: 'heartBeatMethod', realName: 'HeartBeatMethod' },
            { name: 'timeout', realName: 'Timeout' },
            { name: 'playDtmf', realName: 'PlayDtmf' },
            { name: 'hideCallerId', realName: 'HideCallerId' },
            { name: 'record', realName: 'Record' },
            { name: 'recordCallBackUrl', realName: 'RecordCallBackUrl' },
            { name: 'recordCallBackMethod', realName: 'RecordCallBackMethod' },
            { name: 'transcribe', realName: 'Transcribe' },
            { name: 'transcribeCallBackUrl', realName: 'TranscribeCallBackUrl' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body77;
