/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body22
 */
class Body22 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.callSid = this.constructor.getValue(obj.callSid || obj.CallSid);
        this.audioUrl = this.constructor.getValue(obj.audioUrl || obj.AudioUrl);
        this.sayText = this.constructor.getValue(obj.sayText || obj.SayText);
        this.length = this.constructor.getValue(obj.length || obj.Length);
        this.direction = this.constructor.getValue(obj.direction || obj.Direction);
        this.mix = this.constructor.getValue(obj.mix || obj.Mix);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'callSid', realName: 'CallSid' },
            { name: 'audioUrl', realName: 'AudioUrl' },
            { name: 'sayText', realName: 'SayText' },
            { name: 'length', realName: 'Length' },
            { name: 'direction', realName: 'Direction' },
            { name: 'mix', realName: 'Mix' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body22;
