/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body68
 */
class Body68 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.firstName = this.constructor.getValue(obj.firstName || obj.FirstName);
        this.lastName = this.constructor.getValue(obj.lastName || obj.LastName);
        this.email = this.constructor.getValue(obj.email || obj.Email);
        this.friendlyName = this.constructor.getValue(obj.friendlyName || obj.FriendlyName);
        this.password = this.constructor.getValue(obj.password || obj.Password);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'firstName', realName: 'FirstName' },
            { name: 'lastName', realName: 'LastName' },
            { name: 'email', realName: 'Email' },
            { name: 'friendlyName', realName: 'FriendlyName' },
            { name: 'password', realName: 'Password' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body68;
