/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body24
 */
class Body24 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.callSid = this.constructor.getValue(obj.callSid || obj.CallSid);
        this.audioDirection = this.constructor.getValue(obj.audioDirection || obj.AudioDirection);
        this.pitchSemiTones = this.constructor.getValue(obj.pitchSemiTones || obj.PitchSemiTones);
        this.pitchOctaves = this.constructor.getValue(obj.pitchOctaves || obj.PitchOctaves);
        this.pitch = this.constructor.getValue(obj.pitch || obj.Pitch);
        this.rate = this.constructor.getValue(obj.rate || obj.Rate);
        this.tempo = this.constructor.getValue(obj.tempo || obj.Tempo);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'callSid', realName: 'CallSid' },
            { name: 'audioDirection', realName: 'AudioDirection' },
            { name: 'pitchSemiTones', realName: 'PitchSemiTones' },
            { name: 'pitchOctaves', realName: 'PitchOctaves' },
            { name: 'pitch', realName: 'Pitch' },
            { name: 'rate', realName: 'Rate' },
            { name: 'tempo', realName: 'Tempo' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body24;
