/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body28
 */
class Body28 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.callSid = this.constructor.getValue(obj.callSid || obj.CallSid);
        this.url = this.constructor.getValue(obj.url || obj.Url);
        this.method = this.constructor.getValue(obj.method || obj.Method);
        this.status = this.constructor.getValue(obj.status || obj.Status);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'callSid', realName: 'CallSid' },
            { name: 'url', realName: 'Url' },
            { name: 'method', realName: 'Method' },
            { name: 'status', realName: 'Status' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body28;
