/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body52
 */
class Body52 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.shortcode = this.constructor.getValue(obj.shortcode);
        this.to = this.constructor.getValue(obj.to);
        this.body = this.constructor.getValue(obj.body);
        this.method = this.constructor.getValue(obj.method);
        this.messagestatuscallback = this.constructor.getValue(obj.messagestatuscallback);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'shortcode', realName: 'shortcode' },
            { name: 'to', realName: 'to' },
            { name: 'body', realName: 'body' },
            { name: 'method', realName: 'method' },
            { name: 'messagestatuscallback', realName: 'messagestatuscallback' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body52;
