/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body55
 */
class Body55 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.from = this.constructor.getValue(obj.from || obj.From);
        this.to = this.constructor.getValue(obj.to || obj.To);
        this.method = this.constructor.getValue(obj.method || obj.Method);
        this.statusCallBackUrl =
          this.constructor.getValue(obj.statusCallBackUrl
     || obj.StatusCallBackUrl);
        this.statusCallBackMethod =
          this.constructor.getValue(obj.statusCallBackMethod
     || obj.StatusCallBackMethod);
        this.fallbackUrl = this.constructor.getValue(obj.fallbackUrl || obj.FallbackUrl);
        this.fallbackMethod = this.constructor.getValue(obj.fallbackMethod || obj.FallbackMethod);
        this.record = this.constructor.getValue(obj.record || obj.Record);
        this.recordCallBackUrl =
          this.constructor.getValue(obj.recordCallBackUrl
     || obj.RecordCallBackUrl);
        this.recordCallBackMethod =
          this.constructor.getValue(obj.recordCallBackMethod
     || obj.RecordCallBackMethod);
        this.scheduleTime = this.constructor.getValue(obj.scheduleTime || obj.ScheduleTime);
        this.timeout = this.constructor.getValue(obj.timeout || obj.Timeout);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'from', realName: 'From' },
            { name: 'to', realName: 'To' },
            { name: 'method', realName: 'Method' },
            { name: 'statusCallBackUrl', realName: 'StatusCallBackUrl' },
            { name: 'statusCallBackMethod', realName: 'StatusCallBackMethod' },
            { name: 'fallbackUrl', realName: 'FallbackUrl' },
            { name: 'fallbackMethod', realName: 'FallbackMethod' },
            { name: 'record', realName: 'Record' },
            { name: 'recordCallBackUrl', realName: 'RecordCallBackUrl' },
            { name: 'recordCallBackMethod', realName: 'RecordCallBackMethod' },
            { name: 'scheduleTime', realName: 'ScheduleTime' },
            { name: 'timeout', realName: 'Timeout' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body55;
