/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body49
 */
class Body49 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.productCode = this.constructor.getValue(obj.productCode || obj.ProductCode);
        this.startDate = this.constructor.getValue(obj.startDate);
        this.endDate = this.constructor.getValue(obj.endDate);
        this.includeSubAccounts =
          this.constructor.getValue(obj.includeSubAccounts
     || obj.IncludeSubAccounts);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'productCode', realName: 'ProductCode' },
            { name: 'startDate', realName: 'startDate' },
            { name: 'endDate', realName: 'endDate' },
            { name: 'includeSubAccounts', realName: 'IncludeSubAccounts' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body49;
