/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body23
 */
class Body23 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.callSid = this.constructor.getValue(obj.callSid || obj.CallSid);
        this.record = this.constructor.getValue(obj.record || obj.Record);
        this.direction = this.constructor.getValue(obj.direction || obj.Direction);
        this.timeLimit = this.constructor.getValue(obj.timeLimit || obj.TimeLimit);
        this.callBackUrl = this.constructor.getValue(obj.callBackUrl || obj.CallBackUrl);
        this.fileformat = this.constructor.getValue(obj.fileformat || obj.Fileformat);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'callSid', realName: 'CallSid' },
            { name: 'record', realName: 'Record' },
            { name: 'direction', realName: 'Direction' },
            { name: 'timeLimit', realName: 'TimeLimit' },
            { name: 'callBackUrl', realName: 'CallBackUrl' },
            { name: 'fileformat', realName: 'Fileformat' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body23;
