/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body43
 */
class Body43 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.from = this.constructor.getValue(obj.from || obj.From);
        this.rVMCallerId = this.constructor.getValue(obj.rVMCallerId || obj.RVMCallerId);
        this.to = this.constructor.getValue(obj.to || obj.To);
        this.voiceMailURL = this.constructor.getValue(obj.voiceMailURL || obj.VoiceMailURL);
        this.method = this.constructor.getValue(obj.method || obj.Method);
        this.statusCallBackUrl =
          this.constructor.getValue(obj.statusCallBackUrl
     || obj.StatusCallBackUrl);
        this.statsCallBackMethod =
          this.constructor.getValue(obj.statsCallBackMethod
     || obj.StatsCallBackMethod);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'from', realName: 'From' },
            { name: 'rVMCallerId', realName: 'RVMCallerId' },
            { name: 'to', realName: 'To' },
            { name: 'voiceMailURL', realName: 'VoiceMailURL' },
            { name: 'method', realName: 'Method' },
            { name: 'statusCallBackUrl', realName: 'StatusCallBackUrl' },
            { name: 'statsCallBackMethod', realName: 'StatsCallBackMethod' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body43;
