/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body1
 */
class Body1 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.from = this.constructor.getValue(obj.from || obj.From);
        this.to = this.constructor.getValue(obj.to || obj.To);
        this.body = this.constructor.getValue(obj.body || obj.Body);
        this.method = this.constructor.getValue(obj.method || obj.Method);
        this.messageStatusCallback =
          this.constructor.getValue(obj.messageStatusCallback
     || obj.MessageStatusCallback);
        this.smartsms = this.constructor.getValue(obj.smartsms || obj.Smartsms);
        this.deliveryStatus = this.constructor.getValue(obj.deliveryStatus || obj.DeliveryStatus);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'from', realName: 'From' },
            { name: 'to', realName: 'To' },
            { name: 'body', realName: 'Body' },
            { name: 'method', realName: 'Method' },
            { name: 'messageStatusCallback', realName: 'MessageStatusCallback' },
            { name: 'smartsms', realName: 'Smartsms' },
            { name: 'deliveryStatus', realName: 'DeliveryStatus' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body1;
