/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body73
 */
class Body73 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.numberType = this.constructor.getValue(obj.numberType || obj.NumberType);
        this.areaCode = this.constructor.getValue(obj.areaCode || obj.AreaCode);
        this.quantity = this.constructor.getValue(obj.quantity || obj.Quantity);
        this.leftover = this.constructor.getValue(obj.leftover || obj.Leftover);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'numberType', realName: 'NumberType' },
            { name: 'areaCode', realName: 'AreaCode' },
            { name: 'quantity', realName: 'Quantity' },
            { name: 'leftover', realName: 'Leftover' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body73;
