/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body27
 */
class Body27 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.callSid = this.constructor.getValue(obj.callSid || obj.CallSid);
        this.playDtmf = this.constructor.getValue(obj.playDtmf || obj.PlayDtmf);
        this.playDtmfDirection =
          this.constructor.getValue(obj.playDtmfDirection
     || obj.PlayDtmfDirection);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'callSid', realName: 'CallSid' },
            { name: 'playDtmf', realName: 'PlayDtmf' },
            { name: 'playDtmfDirection', realName: 'PlayDtmfDirection' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body27;
