/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Direction1Enum = {

    /**
     * TODO: Write general description for this element
     */
    MIN: 'in',

    /**
     * TODO: Write general description for this element
     */
    OUT: 'out',

    /**
     * TODO: Write general description for this element
     */
    BOTH: 'both',

};

module.exports = Direction1Enum;
