/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Numbertype1Enum = {

    /**
     * TODO: Write general description for this element
     */
    ALL: 'all',

    /**
     * TODO: Write general description for this element
     */
    VOICE: 'voice',

    /**
     * TODO: Write general description for this element
     */
    SMS: 'sms',

};

module.exports = Numbertype1Enum;
