/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Body38 = require('../lib/Models/Body38');
const Body75 = require('../lib/Models/Body75');
const Body1 = require('../lib/Models/Body1');
const Body64 = require('../lib/Models/Body64');
const Body63 = require('../lib/Models/Body63');
const Body22 = require('../lib/Models/Body22');
const Body21 = require('../lib/Models/Body21');
const Body68 = require('../lib/Models/Body68');
const Body24 = require('../lib/Models/Body24');
const Body23 = require('../lib/Models/Body23');
const Body58 = require('../lib/Models/Body58');
const Body52 = require('../lib/Models/Body52');
const Body54 = require('../lib/Models/Body54');
const Body71 = require('../lib/Models/Body71');
const Body55 = require('../lib/Models/Body55');
const Body47 = require('../lib/Models/Body47');
const Body59 = require('../lib/Models/Body59');
const Body14 = require('../lib/Models/Body14');
const Body17 = require('../lib/Models/Body17');
const Body16 = require('../lib/Models/Body16');
const Body19 = require('../lib/Models/Body19');
const Body18 = require('../lib/Models/Body18');
const Body11 = require('../lib/Models/Body11');
const Body10 = require('../lib/Models/Body10');
const Body13 = require('../lib/Models/Body13');
const Body56 = require('../lib/Models/Body56');
const Body12 = require('../lib/Models/Body12');
const Body39 = require('../lib/Models/Body39');
const Body73 = require('../lib/Models/Body73');
const Body6 = require('../lib/Models/Body6');
const Body5 = require('../lib/Models/Body5');
const Body31 = require('../lib/Models/Body31');
const Body7 = require('../lib/Models/Body7');
const Body33 = require('../lib/Models/Body33');
const Body76 = require('../lib/Models/Body76');
const Body32 = require('../lib/Models/Body32');
const Body4 = require('../lib/Models/Body4');
const Body70 = require('../lib/Models/Body70');
const Body26 = require('../lib/Models/Body26');
const Body28 = require('../lib/Models/Body28');
const Body27 = require('../lib/Models/Body27');
const Body29 = require('../lib/Models/Body29');
const Body62 = require('../lib/Models/Body62');
const Body66 = require('../lib/Models/Body66');
const Body65 = require('../lib/Models/Body65');
const Body60 = require('../lib/Models/Body60');
const Body51 = require('../lib/Models/Body51');
const Body50 = require('../lib/Models/Body50');
const Body53 = require('../lib/Models/Body53');
const Body57 = require('../lib/Models/Body57');
const Body48 = require('../lib/Models/Body48');
const Body49 = require('../lib/Models/Body49');
const Body40 = require('../lib/Models/Body40');
const Body42 = require('../lib/Models/Body42');
const Body41 = require('../lib/Models/Body41');
const Body43 = require('../lib/Models/Body43');
const Body44 = require('../lib/Models/Body44');
const Body46 = require('../lib/Models/Body46');
const Body45 = require('../lib/Models/Body45');
const Body36 = require('../lib/Models/Body36');
const Body72 = require('../lib/Models/Body72');
const Body8 = require('../lib/Models/Body8');
const Body74 = require('../lib/Models/Body74');
const Body30 = require('../lib/Models/Body30');
const Body9 = require('../lib/Models/Body9');
const Body35 = require('../lib/Models/Body35');
const Body34 = require('../lib/Models/Body34');
const Body2 = require('../lib/Models/Body2');
const Body3 = require('../lib/Models/Body3');
const Body69 = require('../lib/Models/Body69');
const Body25 = require('../lib/Models/Body25');
const Body61 = require('../lib/Models/Body61');
const Body20 = require('../lib/Models/Body20');
const Body67 = require('../lib/Models/Body67');
const Body = require('../lib/Models/Body');
const Body77 = require('../lib/Models/Body77');

const classMap = {
    Body38,
    Body75,
    Body1,
    Body64,
    Body63,
    Body22,
    Body21,
    Body68,
    Body24,
    Body23,
    Body58,
    Body52,
    Body54,
    Body71,
    Body55,
    Body47,
    Body59,
    Body14,
    Body17,
    Body16,
    Body19,
    Body18,
    Body11,
    Body10,
    Body13,
    Body56,
    Body12,
    Body39,
    Body73,
    Body6,
    Body5,
    Body31,
    Body7,
    Body33,
    Body76,
    Body32,
    Body4,
    Body70,
    Body26,
    Body28,
    Body27,
    Body29,
    Body62,
    Body66,
    Body65,
    Body60,
    Body51,
    Body50,
    Body53,
    Body57,
    Body48,
    Body49,
    Body40,
    Body42,
    Body41,
    Body43,
    Body44,
    Body46,
    Body45,
    Body36,
    Body72,
    Body8,
    Body74,
    Body30,
    Body9,
    Body35,
    Body34,
    Body2,
    Body3,
    Body69,
    Body25,
    Body61,
    Body20,
    Body67,
    Body,
    Body77,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
